<?php

namespace ContainerKCUYlKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\User\CreateUser' shared autowired service.
     *
     * @return \App\Controller\Action\User\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/User/CreateUser.php';

        return $container->services['App\\Controller\\Action\\User\\CreateUser'] = new \App\Controller\Action\User\CreateUser(($container->privates['App\\Service\\User\\UserCreateService'] ?? $container->load('getUserCreateServiceService')));
    }
}
