<?php

namespace ContainerKCUYlKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCreateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Product\ProductCreateService' shared autowired service.
     *
     * @return \App\Service\Product\ProductCreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Product/ProductCreateService.php';

        return $container->privates['App\\Service\\Product\\ProductCreateService'] = new \App\Service\Product\ProductCreateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
