<?php

namespace ContainerKCUYlKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\Authorization\Voter\ProductVoter' shared autowired service.
     *
     * @return \App\Security\Authorization\Voter\ProductVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Authorization/Voter/ProductVoter.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Roles/RolesService.php';

        return $container->privates['App\\Security\\Authorization\\Voter\\ProductVoter'] = new \App\Security\Authorization\Voter\ProductVoter(($container->privates['App\\Service\\Roles\\RolesService'] ?? ($container->privates['App\\Service\\Roles\\RolesService'] = new \App\Service\Roles\RolesService())));
    }
}
