<?php

namespace ContainerKCUYlKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolesServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Roles\RolesService' shared autowired service.
     *
     * @return \App\Service\Roles\RolesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Roles/RolesService.php';

        return $container->privates['App\\Service\\Roles\\RolesService'] = new \App\Service\Roles\RolesService();
    }
}
