<?php

namespace ContainerKCUYlKB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_GetIncidentsIdService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.getIncidentsId' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.getIncidentsId'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('getIncidentsId', 'security.user_checker', '.security.request_matcher.XedioR8', false, false, NULL, NULL, NULL, NULL, NULL, [], NULL);
    }
}
