<?php

namespace Container6Rt1ZFO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateIncidentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\Incident\CreateIncident' shared autowired service.
     *
     * @return \App\Controller\Action\Incident\CreateIncident
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Incident/CreateIncident.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Incident/IncidentCreateService.php';

        return $container->services['App\\Controller\\Action\\Incident\\CreateIncident'] = new \App\Controller\Action\Incident\CreateIncident(new \App\Service\Incident\IncidentCreateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));
    }
}
