<?php

namespace Container6Rt1ZFO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncidentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K_QFTzm.App\Entity\Incident' shared service.
     *
     * @return \App\Entity\Incident
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.K_QFTzm": it references class "App\\Entity\\Incident" but no such service exists.');
    }
}
