<?php

namespace ContainerZdnuNSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateIncidentService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\Incident\CreateIncident' shared autowired service.
     *
     * @return \App\Controller\Action\Incident\CreateIncident
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Incident/CreateIncident.php';

        return $container->services['App\\Controller\\Action\\Incident\\CreateIncident'] = new \App\Controller\Action\Incident\CreateIncident(($container->privates['App\\Service\\Incident\\IncidentCreateService'] ?? $container->load('getIncidentCreateServiceService')));
    }
}
