<?php

namespace ContainerZdnuNSE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipTestFixtures_ServicesDatabaseTools_MongodbDatabaseToolService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'liip_test_fixtures.services_database_tools.mongodb_database_tool' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\DatabaseTools\MongoDBDatabaseTool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/AbstractDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/MongoDBDatabaseTool.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/test-fixtures-bundle/src/Services/FixturesLoaderFactory.php';

        return $container->privates['liip_test_fixtures.services_database_tools.mongodb_database_tool'] = new \Liip\TestFixturesBundle\Services\DatabaseTools\MongoDBDatabaseTool($container, ($container->services['liip_test_fixtures.services.fixtures_loader_factory'] ?? ($container->services['liip_test_fixtures.services.fixtures_loader_factory'] = new \Liip\TestFixturesBundle\Services\FixturesLoaderFactory($container, NULL))));
    }
}
