<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdnuNSE\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdnuNSE/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZdnuNSE.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZdnuNSE\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZdnuNSE\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZdnuNSE',
    'container.build_id' => '20a6057c',
    'container.build_time' => 1610615813,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdnuNSE');
