#################################### USERS #########################################

POST http://localhost:350/api/users/create
Content-Type: application/json

{
  "name": "Admin",
  "password": "Nodriza@01@Admin",
  "roles": [
    "ROLE_ADMIN"
  ]
}

####################

POST http://localhost:350/api/users/create
Content-Type: application/json

{
  "name": "PruebaUsuario2",
  "password": "PruebaContraseña2!",
  "roles": [
    "ROLE_EMPRESA_Tuup"
  ]
}

####################

GET http://localhost:350/api/users/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Nodriza@01@Admin"
}

####################

GET http://localhost:350/api/users/login
Content-Type: application/json

{
  "username": "Peter",
  "password": "password"
}

####################

GET http://localhost:350/api/users/c7c5371d-1a5e-4f4b-aefd-5bdfb8cc8454

####################

DELETE http://localhost:350/api/users/77abaf8c-287a-4fa0-a030-19fd8b5ac8d5

####################

PUT http://localhost:350/api/users/184a312c-ff1f-4fcf-b2e9-d09938f217df
Content-Type: application/json

{
  "name": "PruebaUsuario3",
  "roles": [
    "ROLE_PRUEBA"
  ]
}

####################

GET http://localhost:350/api/users







#################################### PRODUCTS #########################################

POST http://localhost:350/api/products/create
Content-Type: application/json

{
  "name": "PruebaProducto"
}

####################

DELETE http://localhost:350/api/products/8dd2a4a9-8342-4f17-9d94-a4b62dd34978

####################

GET http://localhost:350/api/products

####################

GET http://localhost:350/api/products/general

####################

GET http://localhost:350/api/products/names

####################

GET http://localhost:350/api/products/47068cbf-ca7f-4f0e-b978-21280a8f5cca/services







#################################### SERVICES #########################################

POST http://localhost:350/api/services/create
Content-Type: application/json

{
  "name": "PruebaService",
  "product": "/api/products/0d50d0c0-f29a-4f2f-8eb5-0dfe5e79196d"
}

####################

PUT http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f
Content-Type: application/json

{
  "name": "PruebaService2"
}

####################

DELETE http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f

####################

GET http://localhost:350/api/services/522ea4dd-60d0-4f2d-96f8-8b21f0787b70

####################

GET http://localhost:350/api/services

####################

GET http://localhost:350/api/services/5cf4ab03-f713-4fcd-9af6-0bca26abc721/incidents

####################







#################################### INCIDENTS #########################################

POST http://localhost:350/api/incidents/create
Content-Type: application/json

{
  "name": "PruebaIncident2",
  "information": "info",
  "state": "En investigación",
  "gravity": "Media",
  "services": [
    "/api/services/d1d424b3-3ab8-4f1e-9937-16412a7c79cc"
  ]
}

####################

GET http://localhost:350/api/incidents/f00bf14a-16bd-4fbe-93ea-0ca9f423dfb9.json

####################

PUT http://localhost:350/api/incidents/3605d114-63de-4f34-a50f-f00294d183be
Content-Type: application/json

{
  "name": "PruebaIncident",
  "information": "info",
  "state": "En investigación",
  "gravity": "Media",
  "services": [
    "/api/services/08e52164-e5a6-4fff-ade1-0795f6a73d5f",
    "/api/services/33c08af3-ae85-4f43-b13c-a7a2ca228010"
  ]
}

####################

DELETE http://localhost:350/api/incidents/7167f988-6ead-4f07-b4ad-c005aa608e29

####################

GET http://localhost:350/api/incidents

####################

GET http://localhost:350/api/incidents/74b6ad85-8f54-4fcd-b7f2-7614ad1d642d/services

####################
