#################################### USERS #########################################

POST http://localhost:350/api/users/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDk4MzQ3MTgsImV4cCI6MTYxNTAxODcxOCwidXNlcm5hbWUiOiJBZG1pbiIsImlkIjoiMTg0YTMxMmMtZmYxZi00ZmNmLWIyZTktZDA5OTM4ZjIxN2RmIn0.Q608PyjMEi4gBInCXmJtgspRgTzlbLnxTz5eUjdhfMpoxCXoI4X6XNOL_8BB9Ni-Yl3RfxnuARqDhc3I5K4xHitKeLoiha2Mvay-mnfIHr4Tvnc5qyvRaSqFEAbpCiJl7kGAcLcDq2A_3-zG4O-ZznamdlirHcLWEYrMjnfsTs56m8ALUePM7z1qMERx5myki39YsCzqjg7-OY-TyKU73SPYpfPd3Omu2zoZrn9s6TrsYr2NUZHiFb7InOw_WhTPY3CfJN289XeRLP45om89Rp1fUGnpoBVzrIKtnNzgRIFFMX6SHPGBYV3uyq5b0fTBDnsFfxVWfnsbn3YnK4QtYDEc0bE35BstH5V-JOIcKBB-byAy5PTiKXEpuOwLP-hUl-vW0OneAkgMdN1U0POby3BcjPaF43WP8dVQgLLJIRX57kB6jqU6s8jxdO-Z8BYh2fExGDawxQUIXY2AJF_uuYq6T1aP2TWOjwEqlNLp-4Viu1xC_0N8J2nSLjCuOr5hqTRmP5agMdbDAQ5wneJyBrvznePFHiLmUWLDAaTD8YLxroFTZOu1XYRgirgQkosfFvPrHrcpNEHriEsXquZeGMKdvTT07Jcrt8RNrPFMXBHmE86_LMsX0BQbBakqY7d79Toq94voi_kguZQBUQ4L1-930Ze6Htn3ynYk_y6Q5bI
Content-Type: application/json

{
  "name": "PruebaUsuario2",
  "password": "PruebaContraseña2!",
  "roles": [
    "ROLE_EMPRESA_Tuup"
  ]
}

####################

GET http://localhost:350/api/users/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Nodriza@01@Admin"
}

####################

GET http://localhost:350/api/users/login
Content-Type: application/json

{
  "username": "PruebaUsuario2",
  "password": "PruebaContraseña2!"
}

####################

GET http://localhost:350/api/users/184a312c-ff1f-4fcf-b2e9-d09938f217df

####################

DELETE http://localhost:350/api/users/77abaf8c-287a-4fa0-a030-19fd8b5ac8d5

####################

PUT http://localhost:350/api/users/184a312c-ff1f-4fcf-b2e9-d09938f217df
Content-Type: application/json

{
  "name": "PruebaUsuario3",
  "roles": [
    "ROLE_PRUEBA"
  ]
}

####################

GET http://localhost:350/api/users







#################################### PRODUCTS #########################################

POST http://localhost:350/api/products/create
Content-Type: application/json

{
  "name": "PruebaProducto"
}

####################

DELETE http://localhost:350/api/products/8dd2a4a9-8342-4f17-9d94-a4b62dd34978

####################

GET http://localhost:350/api/products

####################

GET http://localhost:350/api/products/general

####################

GET http://localhost:350/api/products/names

####################

GET http://localhost:350/api/products/47068cbf-ca7f-4f0e-b978-21280a8f5cca/services







#################################### SERVICES #########################################

POST http://localhost:350/api/services/create
Content-Type: application/json

{
  "name": "PruebaService",
  "product": "/api/products/8dd2a4a9-8342-4f17-9d94-a4b62dd34978"
}

####################

PUT http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f
Content-Type: application/json

{
  "name": "PruebaService2"
}

####################

DELETE http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f

####################

GET http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f

####################

GET http://localhost:350/api/services

####################

GET http://localhost:350/api/services/1572231b-8461-4fdf-b759-972a61a00c8f/incidents

####################







#################################### INCIDENTS #########################################

POST http://localhost:350/api/incidents/create
Content-Type: application/json

{
  "name": "PruebaIncident",
  "information": "info",
  "state": "En investigación",
  "gravity": "Baja",
  "services": [
    "/api/services/1572231b-8461-4fdf-b759-972a61a00c8f"
  ]
}

####################

GET http://localhost:350/api/incidents/74b6ad85-8f54-4fcd-b7f2-7614ad1d642d

####################

PUT http://localhost:350/api/incidents/74b6ad85-8f54-4fcd-b7f2-7614ad1d642d
Content-Type: application/json

{
  "name": "PruebaIncident2",
  "information": "info",
  "state": "En investigación",
  "gravity": "Baja",
  "services": [
    "/api/services/1572231b-8461-4fdf-b759-972a61a00c8f"
  ]
}

####################

DELETE http://localhost:350/api/incidents/74b6ad85-8f54-4fcd-b7f2-7614ad1d642d

####################

GET http://localhost:350/api/incidents

####################

GET http://localhost:350/api/incidents/74b6ad85-8f54-4fcd-b7f2-7614ad1d642d/services

####################
