api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: NODRIZAstatus API Platform
    version: 1.0
    show_webby: false

#    formats:
#        json: [ 'application/json' ]
#        jsonld: [ 'application/ld+json' ]
