<?php

namespace ContainerFZ8dt73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TO3kXqKService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.TO3kXqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TO3kXqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.TO3kXqK.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.TO3kXqK": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\User',
        ]);
    }
}
