<?php

namespace ContainerFZ8dt73;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\Service\CreateService' shared autowired service.
     *
     * @return \App\Controller\Action\Service\CreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Service/CreateService.php';

        return $container->services['App\\Controller\\Action\\Service\\CreateService'] = new \App\Controller\Action\Service\CreateService(($container->privates['App\\Service\\Service\\ServiceCreateService'] ?? $container->load('getServiceCreateServiceService')));
    }
}
