<?php

namespace ContainerZmpPgfq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1ijW05Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1ijW05' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k1ijW05'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'data' => ['privates', '.errored..service_locator.k1ijW05.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.k1ijW05": it references class "App\\Entity\\Service" but no such service exists.'],
        ], [
            'data' => 'App\\Entity\\Service',
        ]);
    }
}
