<?php

namespace ContainerZmpPgfq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\Service\CreateService' shared autowired service.
     *
     * @return \App\Controller\Action\Service\CreateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Service/CreateService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Service/ServiceCreateService.php';

        return $container->services['App\\Controller\\Action\\Service\\CreateService'] = new \App\Controller\Action\Service\CreateService(new \App\Service\Service\ServiceCreateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));
    }
}
