<?php

namespace ContainerXbxONBI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Controller\Listener\ServiceNotifier' shared autowired service.
     *
     * @return \App\Controller\Listener\ServiceNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Listener/ServiceNotifier.php';

        return $container->privates['App\\Controller\\Listener\\ServiceNotifier'] = new \App\Controller\Listener\ServiceNotifier(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
