App\Entity\Incident:
  attributes:
    normalization_context:
      groups: [incident_read]
  collectionOperations:
    get: ~

    register:
      method: POST
      path: /incidents/create
      controller: App\Controller\Action\Incident\CreateIncident
      denormalization_context:
        groups: [ incident_post ]
      security_post_denormalize: is_granted("INCIDENT_CREATE", object)
      security_post_denormalize_message: 'Wrong Permissions, You can not create an Incident'
      openapi_context:
        summary: Create a new Incident

  itemOperations:
    get: ~

    put:
      method: PUT
      security: is_granted("INCIDENT_UPDATE")
      security_message: 'Wrong Permissions, You can not update an Incident'
      denormalization_context:
        groups: [ incident_update ]

    delete:
      method: DELETE
      security: is_granted("INCIDENT_DELETE")
      security_message: 'Wrong Permissions, You can not delete an Incident'

  properties:
    services:
      subresource:
        resourceClass: App\Entity\Service
        collection: true
        maxDepth: 1