App\Entity\Product:
  attributes:
    normalization_context:
      groups: [product_read]
  collectionOperations:
    register:
      method: POST
      path: /products/create
      controller: App\Controller\Action\Product\CreateProduct
      denormalization_context:
        groups: [product_post]
      security_post_denormalize: is_granted("PRODUCT_CREATE", object)
      security_post_denormalize_message: 'Wrong Permissions, You can not create a Product'
      openapi_context:
        summary: Create a new Product

    names:
      method: GET
      path: /products/names
      controller: App\Controller\Action\Product\NameProduct
      deserialize: false
      openapi_context:
        summary: Product names

    generalState:
      method: GET
      path: /products/general
      controller: App\Controller\Action\Product\GeneralState
      deserialize: false
      openapi_context:
        summary: Nodriza's General State

    get: ~

  itemOperations:
    get: ~

    delete:
      method: DELETE
      security: is_granted("PRODUCT_DELETE")
      security_message: 'Wrong Permissions, You can not delete a Product'

  properties:
    services:
      subresource:
        resourceClass: App\Entity\Service
        collection: true
        maxDepth: 1