App\Entity\User:
  attributes:
    id:
      groups: [ user_read ]
    name:
      groups: [ user_read, user_post, user_update ]
    password:
      groups: [ user_read, user_post ]
    roles:
      groups: [ user_read, user_post, user_update ]
    createdAt:
      groups: [ user_read ]
    updatedAt:
      groups: [ user_read ]