<?php

namespace ContainerPAANHAe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncoderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Password\EncoderService' shared autowired service.
     *
     * @return \App\Service\Password\EncoderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Password/EncoderService.php';

        return $container->privates['App\\Service\\Password\\EncoderService'] = new \App\Service\Password\EncoderService(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
