<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zkuuOQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zkuuOQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6zkuuOQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6zkuuOQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6zkuuOQ\App_KernelDevDebugContainer([
    'container.build_hash' => '6zkuuOQ',
    'container.build_id' => 'b67abaf1',
    'container.build_time' => 1609337319,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zkuuOQ');
