<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3vZPR4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3vZPR4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG3vZPR4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG3vZPR4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG3vZPR4\App_KernelDevDebugContainer([
    'container.build_hash' => 'G3vZPR4',
    'container.build_id' => 'ff96a965',
    'container.build_time' => 1609331448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3vZPR4');
