<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL3xLzxL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL3xLzxL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL3xLzxL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL3xLzxL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL3xLzxL\App_KernelDevDebugContainer([
    'container.build_hash' => 'L3xLzxL',
    'container.build_id' => '46f4ab4c',
    'container.build_time' => 1609413219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL3xLzxL');
