<?php

namespace ContainerYtvkpvn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNameProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\Product\NameProduct' shared autowired service.
     *
     * @return \App\Controller\Action\Product\NameProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Product/NameProduct.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Product/ProductNameService.php';

        return $container->services['App\\Controller\\Action\\Product\\NameProduct'] = new \App\Controller\Action\Product\NameProduct(new \App\Service\Product\ProductNameService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'))));
    }
}
