<?php

namespace ContainerG3vZPR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\User\UpdateUser' shared autowired service.
     *
     * @return \App\Controller\Action\User\UpdateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/User/UpdateUser.php';
        include_once \dirname(__DIR__, 4).'/src/Service/User/UserUpdateService.php';

        return $container->services['App\\Controller\\Action\\User\\UpdateUser'] = new \App\Controller\Action\User\UpdateUser(new \App\Service\User\UserUpdateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\Password\\EncoderService'] ?? $container->load('getEncoderServiceService'))));
    }
}
