<?php

namespace ContainerWuZl9sQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Action\User\CreateUser' shared autowired service.
     *
     * @return \App\Controller\Action\User\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/User/CreateUser.php';
        include_once \dirname(__DIR__, 4).'/src/Service/User/UserCreateService.php';

        return $container->services['App\\Controller\\Action\\User\\CreateUser'] = new \App\Controller\Action\User\CreateUser(new \App\Service\User\UserCreateService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\Password\\EncoderService'] ?? $container->load('getEncoderServiceService'))));
    }
}
